### ISSUE TITLE
Dockerfile for easier self-hosted deployment

### ISSUE THREAD

**Issue by TheAnachronism** [ndom91/briefkasten#9]
### Clear and concise description of the problem

Like for many other self-hosted applications, it is far easier to do that if there's a Dockerfile or an image directly available.
Of course, making an image publicly available through, for example, Docker hub isn't that necessary, but at least a Dockerfile should be made available.

### Suggested solution

I, personally, have written some Dockerfiles myself, so I could create an initial one, and we can further discuss on how to improve it.
I'll create a PR for it, and we can discuss it in there.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
Yes, very good idea! I'll come up with an initial one myself. Feel free to put up a PR to suggest any improvements :+1:

**Comment by ndom91** [comment]
I created a WIP PR: https://github.com/ndom91/briefkasten/pull/10

Currently stuck due to the fact that the build of `briefkasten` service runs before the `postgres` service, even though `briefkasten` `depends_on: postgres`. 

This is a problem, because in the build of the `briefkasten` service (next.js app), the prisma migrations can't run on a database that is not up yet..
